In [3]:
import numpy as np

In [6]:
m=np.random.randint(0,10,(3,3))
m

array([[4, 7, 1],
       [7, 9, 5],
       [8, 2, 0]], dtype=int32)

In [9]:
m[1,2]

np.int32(5)

In [10]:
m[1,2]=2.2 #Ondalık kısmını attı
m

array([[4, 7, 1],
       [7, 9, 2],
       [8, 2, 0]], dtype=int32)

In [11]:
m

array([[4, 7, 1],
       [7, 9, 2],
       [8, 2, 0]], dtype=int32)

In [ ]:
#İki boyutlu SLİCE işlemleri

In [12]:
m[:,1:]

array([[7, 1],
       [9, 2],
       [2, 0]], dtype=int32)

In [16]:
m[1:,0]

array([7, 8], dtype=int32)

In [17]:
m[:,2:]

array([[1],
       [2],
       [0]], dtype=int32)

In [18]:
m[1,1:]

array([9, 2], dtype=int32)

In [20]:
a=np.random.randint(0,10,(5,5))
a

array([[5, 8, 9, 8, 1],
       [2, 6, 6, 3, 8],
       [5, 3, 6, 3, 5],
       [6, 9, 5, 6, 4],
       [4, 6, 0, 8, 1]], dtype=int32)

In [22]:
aAltkume=a[:,1:3].copy()
aAltkume

array([[8, 9],
       [6, 6],
       [3, 6],
       [9, 5],
       [6, 0]], dtype=int32)

In [23]:
aAltkume[0,1]=7
aAltkume

array([[8, 7],
       [6, 6],
       [3, 6],
       [9, 5],
       [6, 0]], dtype=int32)

In [24]:
a #copy yaptıgımız için ana kumede değişiklik olmadı copy kullanmasaydık ana arrayde değişiklik gerçekleşecekti

array([[5, 8, 9, 8, 1],
       [2, 6, 6, 3, 8],
       [5, 3, 6, 3, 5],
       [6, 9, 5, 6, 4],
       [4, 6, 0, 8, 1]], dtype=int32)

**FANCY İNDEX İLE ELEMANLARA ERİŞMEK**

In [30]:
array=np.arange(0,30,3)
array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [66]:
al_getir=[1,3,5] #TEK BOYUTTA FANCY
array[al_getir]

array([ 3,  9, 15])

In [8]:
#İKİ BOYUTTA FANCY
k=np.arange(0,9).reshape(3,3)
k

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
satir=[0,0,2]
sutun=[1,1,0]
k[satir,sutun]

array([1, 1, 6])

In [10]:
k[[0,0],[1,1]]

array([1, 1])

In [37]:
#Basit index ile fancy index

In [11]:
k

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
k[1,[1,2]]   

array([4, 5])

In [ ]:
#Slice ile fancy index

In [40]:
k[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

**Koşullu Eleman İşlemleri**

In [4]:
v=np.array([1,2,3,4,5])

In [43]:
v>3

array([False, False, False,  True,  True])

In [45]:
v[v>3]

array([3])

In [46]:
v[v!=3]

array([1, 2, 4, 5])

In [47]:
v[v==3]

array([3])

In [48]:
v

array([1, 2, 3, 4, 5])

In [49]:
v*2

array([ 2,  4,  6,  8, 10])

In [50]:
v**2

array([ 1,  4,  9, 16, 25])

In [51]:
v-2

array([-1,  0,  1,  2,  3])

In [52]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

** Herhangi bir kütüphanenin/dilin derli toplu dökümantasyonuna ulaşmak istiyorsak cheat sheet yani kopya kağıdı diye sonuna ekleyerek aratırız 
numpy mathematics cheat sheet gibisinden aratabiliriz. veya numpy statistics cheat sheet vs. !!!!!!!!!!!!!!!!!!!!! **

In [5]:
v


array([1, 2, 3, 4, 5])

In [6]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [55]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [57]:
np.divide(v,2)

array([0.5, 1. , 1.5, 2. , 2.5])

In [7]:
np.multiply(v,2)

array([ 2,  4,  6,  8, 10])

In [59]:
np.mean(v) #3

np.float64(3.0)

** Numpy ile iki bilinmeyenli denklem çözümü **

5*x0 + x1 = 12
x0 + 3*x1 = 10

In [61]:
p=np.array([[5,1],[1,3]])

In [62]:
s=np.array([[12],[10]])

In [63]:
np.linalg.solve(p,s)

array([[1.85714286],
       [2.71428571]])