*Ana Başlık*

**Alt Başlık**

-Yazı tipi-

#Sıfırdan array oluşturma

In [2]:
import numpy as np

np kütüphanesinin arrayleri tek bir tip ile çalışır ve bu da verimli veri saklamak demek

In [4]:
np.zeros(10, dtype=int) 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [10]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [4]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [13]:
np.random.normal(50,12,(3,3))

array([[45.79837822, 33.17956196, 56.25623563],
       [59.17372057, 53.83053582, 29.99041901],
       [51.55905792, 35.38999555, 56.16174463]])

In [23]:
np.random.randint(1,30,(3,3))

array([[17,  8, 29],
       [ 6, 27, 13],
       [25, 29,  4]], dtype=int32)

**Özellikleri**

* ndim: boyut sayısı
* shape: boyut bilgisi
* size : toplam eleman sayısı
* dtype : array veri tipi

In [32]:
a = np.random.randint(0,10,3)

In [28]:
a.ndim

1

In [29]:
a.shape

(3,)

In [30]:
a.size

3

In [33]:
a.dtype

dtype('int32')

In [34]:
a = np.random.randint(0,10,(3,3))

In [35]:
a.ndim

2

In [36]:
a.shape

(3, 3)

In [37]:
a.size

9

In [38]:
a.dtype

dtype('int32')

In [39]:
a

array([[2, 9, 1],
       [4, 6, 6],
       [2, 5, 6]], dtype=int32)

In [40]:
a.reshape(9)

array([2, 9, 1, 4, 6, 6, 2, 5, 6], dtype=int32)

In [41]:
a.reshape(1,9)

array([[2, 9, 1, 4, 6, 6, 2, 5, 6]], dtype=int32)

In [42]:
a.reshape(3,3)

array([[2, 9, 1],
       [4, 6, 6],
       [2, 5, 6]], dtype=int32)