In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3])

In [4]:
b = np.array([4,5,6])

In [7]:
a

array([1, 2, 3])

In [6]:
b

array([4, 5, 6])

In [12]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6])

In [16]:
a= np.array([[1,2,3],
            [4,5,6]])

In [17]:
b= np.array([[10,12,13],
            [14,15,16]])

In [18]:
np.concatenate([a,b])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 12, 13],
       [14, 15, 16]])

In [23]:
np.concatenate([a,b],axis=0) #axis eksen belirtmek için kullanılır. 0 satırları,1 ise sütünları belirtir

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 12, 13],
       [14, 15, 16]])

In [22]:
np.concatenate([a,b],axis=1)

array([[ 1,  2,  3, 10, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [32]:
c=np.array([1,3,6,7,45,23,27,32])

In [33]:
np.split(c, [3,5])

[array([1, 3, 6]), array([ 7, 45]), array([23, 27, 32])]

In [34]:
x,y,z = np.split(c, [3,5])

In [35]:
x

array([1, 3, 6])

In [36]:
y

array([ 7, 45])

In [37]:
z

array([23, 27, 32])

In [5]:
m=np.arange(0,16)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [51]:
m.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [6]:
m=m.reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
np.vsplit(m,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [58]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [76]:
upper,under=np.vsplit(m,[2])

In [77]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [78]:
under

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
left,right=np.hsplit(m,[2])

In [68]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [69]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [80]:
u=np.array([32,43,12,34,5,56])

In [81]:
siraliU=np.sort(u) #u.sort() kullansak veri yapısı bozulurdu fakat np sortunu kullanınca veri yapısını bozmadan elde ettik
siraliU

array([ 5, 12, 32, 34, 43, 56])

In [7]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [83]:
siraliM=np.sort(m,axis=0) #axis=0 satırları sıralarken, 1 sütunları sıralar
siraliM

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])